name: Github-Pages-YourProject

on:
  workflow_dispatch:
    inputs:
      banner:
        type: choice
        description: banner
        required: true
        options:
          - Google
      environment:
        type: choice
        description: environment
        required: true
        options:
          - QA1
          - QA2
      application:
        type: choice
        description: application
        required: true
        options:
          - CoreScheduler
      test_type:
        type: choice
        description: test_type
        required: true
        options:
          - DOB1

jobs:
  call-ci-workflow:
    # Replace with the appropriate action for your project
    uses: zaid/esgh-central-workflow-aut/.github/workflows/gradle-automation.yml@v4
    with:
      javaVersion: 8
      args: '-Ptestdata="myteams"-"${{ github.event.inputs.banner }}"_"${{ github.event.inputs.environment }}" -PcucumberTags="@${{ github.event.inputs.test_type }}"'
      test_reports: '**/cucumber-local-reports/cucumber-html-reports/*'

  build:
    runs-on: ubuntu-latest
    needs: [call-ci-workflow]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # Modify the build command according to your project
      - name: Build with Gradle
        run: ./gradlew chromeHeadlessCucumberTest -Ptestdata=myteams-MyTeams_QA -PcucumberTags=@DOB1 generateCucumberReport

  deploy-pages:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: build/reports  # Adjust the folder as needed
          #token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          entry_file: 'index.html'

  send-email-cucumber:
    runs-on: ubuntu-latest
    needs: [deploy-pages]
    if: always()

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: 'smtp.office365.com'
          server_port: 587
          username: '${{ secrets.USERNAME }}'  # Your gmail email address (GitHub secret)
          password: '${{ secrets.PASSWORD }}'  # Your gmail email password (GitHub secret)
          subject: 'Build completed'
          to: 'zaidtahir21@outlook.com'  # Recipient's email address
          from: 'zaidtahir21@outlook.com'  # Your gmail email address
          body: 'The build has completed successfully. Please click the link to view the report: https://pages.github.com/your-org/your-repo/'

