name: Selenium-Github-Pages

on:
  workflow_dispatch:
    inputs:
      banner:
        type: choice
        description: banner
        required: true
        options:
          - Google
      environment:
        type: choice
        description: environment
        required: true
        options:
          - MyTeamsQA
          - MyTeamsUAT
      application:
        type: choice
        description: application
        required: true
        options:
          - CoreScheduler
      test_type:
        type: choice
        description: test_type
        required: true
        options:
          - DOB1
  push:
    branches: ["selenium_githubactions"]
  pull_request:
    branches: ["selenium_githubactions"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Create Cucumber Report Directory
        run: mkdir cucumber-report
      - name: Build and Generate Cucumber Report
        run: ./gradlew chromeHeadlessCucumberTest -Ptestdata=myteams-MyTeams_QA -PcucumberTags=@DOB1 generateCucumberReports

      - name: Print directory contents before archiving
        run: ls -R

      - name: Create a Zip Archive of Cucumber Report
        run: zip -r cucumber-report.zip ./Test/cucumber-local-reports/cucumber-html-reports/

      - name: Archive Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: cucumber-report.zip


  send-email:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
#        - name: Zip Cucumber Report
#          run: zip -r cucumber-report.zip . -i cucumber-report
        - name: Send Email with Cucumber Report
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: 'smtp.office365.com'  # Outlook SMTP server address
            server_port: 587  # SMTP port
            username: '${{ secrets.USERNAME }}'  # Your email address (GitHub secret)
            password: '${{ secrets.PASSWORD }}'  # Your email password (GitHub secret)
            subject: 'Cucumber Report - Build completed'
            to: 'zaidtahir21@outlook.com'  # Recipient's email address
            from: 'zaidtahir21@outlook.com'  # Your email address
            body: 'The build has completed successfully.'
            attachments: './cucumber-report'  # Assuming the artifact was downloaded to this path

