name: Java CI with Gradle

on:
  push:
    branches: [ "selenium_githubactions" ]
  pull_request:
    branches: [ "selenium_githubactions" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew chromeHeadlessCucumberTest -Ptestdata=myteams-MyTeams_QA -PcucumberTags=@DOB1 generateCucumberReport

  send-email:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: 'smtp.office365.com'  # Outlook SMTP server address
          server_port: 587  # Outlook SMTP port
          username: '${{ secrets.USERNAME }}'  # Your Outlook email address (GitHub secret)
          password: '${{ secrets.PASSWORD }}'  # Your Outlook email password (GitHub secret)
          subject: 'Build completed'
          to: 'zaidtahir21@outlook.com'  # Recipient's email address
          from: 'testingemailuser1993@gmail.com'  # Your Outlook email address
          body: 'The build has completed successfully.'