name: RXIE-EngOpsAutomation-UI
on:
  workflow_dispatch:
    inputs:
      banner:
        type: choice
        description: banner
        required: true
        options:
          - Vons
          - JewelOsco
          - Pavillions
          - StarMarket
          - AcmeMarkets
          - CarrsQC
          - TomThumb
          - Randalls
          - Shaws
          - UnitedSuperMarkets
      environment:
        type: choice
        description: environment
        required: true
        options:
          - QA1
          - QA2
      application:
        type: choice
        description: application
        required: true
        options:
          - CoreScheduler
          - CareGiver
          - PetRx
      test_type:
        type: choice
        description: test_type
        required: true
        options:
          - UnifiedFlowSmoke
          - UnifiedFlowRegression
          - GCRegression
          - GCSmoke
          - sampletestgha
          - EndToEnd
          - CoreScheduler
          - GHADEMO
          - GCRegressionNew
          - DOB
  
jobs:
  call-ci-workflow:
    uses: albertsons/esgh-central-workflow-aut/.github/workflows/gradle-automation.yml@v4
    with:
      javaVersion: 8
      args: '-Ptestdata="pharmacy"-"${{ github.event.inputs.banner }}"_"${{ github.event.inputs.environment }}" -PcucumberTags="@${{ github.event.inputs.test_type }}"'
      test_reports: '**/cucumber-local-reports/cucumber-html-reports/*'
  sending-email-cucumber:
    needs: [call-ci-workflow]
    if: always()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Send_Email_Attachment.yml@v4
    with:
      EMAIL_TO: zaidtahir21@outlook.com
      EMAIL_ATTACHMENT: RXIS-UIAutomation.tar.gz
      EMAIL_FROM: malvi14@safeway.com
      FILES: ReportArtifacts
    secrets:
       PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
       EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
       EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  
